ID-1469 added new section for loaders
identity-dev/styleguide pull request #5
Opened 2018-01-24 18:19 UTC by abodnar-svitla

Added new section for loaders

2018-01-25 22:28 UTC, tylerchilds requested changes
When doing button small, the loader overlaps: 
<img width="113" alt="screen shot 2018-01-25 at 2 25 00 pm" src="https://user-images.githubusercontent.com/393448/35415743-8aa9850c-01db-11e8-8be9-5eef87811d5b.png">

This should work for all button sizes. We should also utilize the existing `loader` class and move all of that into the styleguide, since this PR only solves the animated svg issue for buttons. For styling buttons, we should select like we do right now:

```
.loader.btn,
.loader[type=button],
.loader[type=submit],
button.loader{
```

2018-01-26 18:51 UTC, abodnar-svitla commented
@tylerchilds, updated styles for loader

2018-01-30 00:59 UTC, tylerchilds requested changes
A few minor things

2018-01-30 00:59 UTC, tylerchilds commented on src/sass/components/_loader.scss
>      position: absolute;
let's remove 
```
position, top, bottom, right, margin
```

and make `margin-left: 10px`

2018-01-30 00:59 UTC, tylerchilds commented on src/sass/components/_loader.scss
> +    animation: spin 1s linear infinite;
Talked to Hunter, let's do this for easing function: `cubic-bezier(0.35, 0.55, 0.85, 0.95)`

2018-01-30 00:59 UTC, tylerchilds commented on src/sass/components/_loader.scss
> +    padding-right: 30px;
with the above changes, we can remove these padding-right tweaks

2018-01-30 17:45 UTC, abodnar-svitla commented
@tylerchilds, i fixed your comments, could you please check?

2018-01-30 18:24 UTC, tylerchilds requested changes
Final feedback: Just nudge the loaders with position: relative and top to make sure they're vertically centered with the text.

2018-01-30 18:26 UTC, tylerchilds commented on dist/scss/components/_loader.scss
> +  padding-right: 30px;
we'll also want to remove this

2018-01-30 19:01 UTC, tylerchilds approved these changes

2018-01-30 19:01 UTC, merged